name: GetSDK
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start
      run: |
         echo 666
         #sudo docker rmi $(docker images -q)
         sudo apt update
         sudo apt install wget
         wget -O /tmp/a.tar.xz https://litter.catbox.moe/h2put4.xz
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: /tmp/a.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
