name: GetSDK
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start
      run: |
         echo 666
         #sudo docker rmi $(docker images -q)
         sudo apt update
         sudo apt install wget
         wget -O /tmp/a.tar.xz https://litter.catbox.moe/h2put4.xz
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: BB.tar.xz
        path: /tmp/a.tar.xz
